import { useEffect, useState } from "react"

/* Whether anyone is actually trading it.
 *
 * The index answers "what launched and does it look manufactured". It cannot
 * answer "is there a market", and that gap was the whole complaint about the
 * feed: rows of names, tickers and a spam score, with nothing to say whether a
 * token had any traction at all. Our own backend cannot close it either —
 * liquidity on this chain lives in Uniswap V4 behind a singleton PoolManager
 * with no per-pair contract to read, which is exactly why `outcomeSampler`
 * measures transfers instead of price.
 *
 * DexScreener indexes Robinhood Chain and answers it in one call. Verified
 * against the live feed: 25 addresses returned 15 pairs in 391ms, across both
 * DEXes on the chain (uniswap v3/v4 and flapsh), quoted in ETH/WETH.
 *
 * IT RUNS IN THE BROWSER ON PURPOSE. The endpoint sends CORS headers, and its
 * rate limit is per-caller — so client-side it scales with users instead of
 * funnelling every visitor through one server-side quota. Moving it behind our
 * own API later is a change of `fetchMarkets`, nothing else.
 *
 * NO MARKET IS A RESULT, NOT A FAILURE. Most launches genuinely have no pool,
 * which is the product's entire premise: you are seeing them before they have a
 * price. A token with no pair returns undefined here and the UI says so. */

export type Market = {
  address: string
  /* The venue's own name for the token. Carried because the token page must
     still be able to say what it is looking at when our index cannot answer —
     an unknown address is a much worse heading than a ticker. */
  symbol: string
  name: string
  priceUsd: number | null
  liquidityUsd: number | null
  volume24h: number | null
  priceChange24h: number | null
  txns24h: number | null
  marketCap: number | null
  /** The market page, taken from the response. Never constructed by us. */
  url: string
  /** Which DEX the liquidity is actually on. */
  dex: string
  /** Protocol version tags, e.g. ["v3"] or ["v4"]. Decides whether we can
      route a trade in-app or must hand off to the venue. */
  labels: string[]
  /** What the token is paired against. Only a WETH pair can be bought with ETH
      in one hop, so this gates in-app routing alongside the protocol label. */
  quoteToken: string
}

const API = "https://api.dexscreener.com/latest/dex/tokens/"
// The endpoint takes a comma-separated list; 30 is its documented ceiling.
const CHUNK = 25
const TTL_MS = 45_000

type Entry = { at: number; result: { markets: Map<string, Market>; ok: boolean } }
let cache: Entry | null = null
let cacheKey = ""

const num = (v: unknown): number | null => {
  const n = typeof v === "string" ? parseFloat(v) : typeof v === "number" ? v : NaN
  return Number.isFinite(n) ? n : null
}

/* An empty map from a failed request and an empty map from a healthy one mean
   opposite things, so the caller is told which it got. Without this the UI
   asserted "No market yet. Nobody can trade this." on every row of a total
   outage — measured against a window where 11 of 30 had live markets, one at
   $51k liquidity. A claim about the chain generated by a network error is the
   one failure mode this product cannot afford. */
export type MarketResult = { markets: Map<string, Market>; ok: boolean }

export async function fetchMarkets(addresses: string[]): Promise<MarketResult> {
  const out = new Map<string, Market>()
  const unique = [...new Set(addresses.map((a) => a.toLowerCase()))]
  if (!unique.length) return { markets: out, ok: true }

  const chunks: string[][] = []
  for (let i = 0; i < unique.length; i += CHUNK) chunks.push(unique.slice(i, i + CHUNK))

  const responses = await Promise.allSettled(
    chunks.map((c) => fetch(API + c.join(",")).then((r) => (r.ok ? r.json() : Promise.reject(r.status))))
  )

  const ok = responses.some((r) => r.status === "fulfilled")

  for (const r of responses) {
    if (r.status !== "fulfilled") continue
    for (const pair of r.value?.pairs || []) {
      const addr = String(pair?.baseToken?.address || "").toLowerCase()
      if (!addr) continue
      const liquidityUsd = num(pair?.liquidity?.usd)
      const prev = out.get(addr)
      // A token can have several pools. The deepest one is the market that
      // matters, and it is the one a handoff should point at.
      if (prev && (prev.liquidityUsd ?? 0) >= (liquidityUsd ?? 0)) continue
      const buys = num(pair?.txns?.h24?.buys) ?? 0
      const sells = num(pair?.txns?.h24?.sells) ?? 0
      out.set(addr, {
        address: addr,
        symbol: String(pair?.baseToken?.symbol || ""),
        name: String(pair?.baseToken?.name || ""),
        priceUsd: num(pair?.priceUsd),
        liquidityUsd,
        volume24h: num(pair?.volume?.h24),
        priceChange24h: num(pair?.priceChange?.h24),
        txns24h: buys + sells,
        marketCap: num(pair?.marketCap) ?? num(pair?.fdv),
        url: String(pair?.url || ""),
        dex: String(pair?.dexId || ""),
        labels: Array.isArray(pair?.labels) ? pair.labels.map(String) : [],
        quoteToken: String(pair?.quoteToken?.address || "").toLowerCase(),
      })
    }
  }
  return { markets: out, ok }
}

/** Markets for a set of addresses, refreshed with the page. `null` while in
    flight — callers must not read "no market" out of a pending request. */
export function useMarkets(addresses: string[] | null): MarketResult | null {
  const [result, setResult] = useState<MarketResult | null>(null)
  const key = (addresses || []).join(",")

  useEffect(() => {
    // An empty list is a settled answer, not a pending one. Returning without
    // resolving left every consumer holding `null` forever, which rendered
    // skeletons that never stopped pulsing on an empty feed.
    if (!addresses || !addresses.length) {
      setResult({ markets: new Map(), ok: true })
      return
    }
    let alive = true

    if (cache && cacheKey === key && Date.now() - cache.at < TTL_MS) {
      setResult(cache.result)
      return
    }

    fetchMarkets(addresses)
      .then((r) => {
        if (!alive) return
        // Only a good read is worth caching.
        if (r.ok) {
          cache = { at: Date.now(), result: r }
          cacheKey = key
        }
        setResult(r)
      })
      // A missing market layer must never blank a working feed.
      .catch((e) => {
        console.error("[markets] unavailable:", e)
        if (alive) setResult({ markets: new Map(), ok: false })
      })

    return () => {
      alive = false
    }
  }, [key])

  return result
}

/* Compact money. $36,144 is four glyphs of noise in a row that has to scan. */
export function usd(n: number | null): string {
  if (n === null) return "—"
  if (n >= 1_000_000) return `$${(n / 1_000_000).toFixed(n >= 10_000_000 ? 0 : 1)}M`
  if (n >= 1_000) return `$${(n / 1_000).toFixed(n >= 10_000 ? 0 : 1)}k`
  return `$${n.toFixed(0)}`
}
